-- =============================================================================
-- JobRadar Automation Intelligence Hub — PostgreSQL Schema
-- Version: 1.1
-- Updated: 2026-06-08
-- =============================================================================
-- Table hierarchy:
--   companies → employers → jobs → job_events
--
-- Design decisions:
--   - job_id_fuzzy / job_thread_key are the dedup keys produced by Claude.
--     Actual dedup logic (ON CONFLICT, upsert) lives in n8n or DB triggers.
--   - raw_text is stored inline (TEXT). For blobs > 64KB, store a
--     raw_storage_ref (Telegram file_id or S3 key) instead.
--   - user_rating is NOT set by AI — always updated by the user.
--   - All timestamps in UTC.
--
-- Security design:
--   - tenant_id on all tables — multi-tenant ready (RLS stubs included).
--   - Separate DB roles: jobradar_app (rw), jobradar_readonly (r).
--   - All application queries MUST use parameterized statements ($1, $2 ...).
--     No string interpolation into SQL — ever.
--   - job_events is append-only (immutable audit log). No DELETEs.
--   - raw_text may contain PII — consider encryption at rest (VPS disk enc).
--
-- Scale design:
--   - Indexes on all FK columns and common filter columns.
--   - pg_trgm for fuzzy job title search.
--   - PgBouncer recommended in front (transaction mode, port 6432).
--   - RLS disabled by default — enable per-table when adding second tenant.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";   -- for fuzzy text search on job titles

-- ---------------------------------------------------------------------------
-- ENUM types
-- ---------------------------------------------------------------------------

CREATE TYPE input_source_enum AS ENUM ('email', 'scraped', 'manual');

CREATE TYPE job_category_enum AS ENUM (
  'hr_invite', 'interview_invite', 'test_task', 'offer',
  'rejection', 'follow_up', 'job_posting', 'newsletter',
  'platform_notification', 'manual_note', 'other'
);

CREATE TYPE job_stage_enum AS ENUM (
  'discovered', 'applied', 'screening', 'interview',
  'test_task', 'offer', 'rejected', 'withdrawn', 'on_hold',
  'application_failed'
);

CREATE TYPE priority_enum AS ENUM ('high', 'medium', 'low');

CREATE TYPE call_platform_enum AS ENUM (
  'zoom', 'teams', 'google_meet', 'phone', 'in_person', 'other'
);

CREATE TYPE work_mode_enum AS ENUM ('remote', 'hybrid', 'onsite');

CREATE TYPE salary_period_enum AS ENUM ('monthly', 'annual', 'hourly');

CREATE TYPE seniority_enum AS ENUM (
  'intern', 'junior', 'middle', 'senior',
  'lead', 'principal', 'staff', 'director'
);

CREATE TYPE user_rating_enum AS ENUM ('unknown', 'green', 'neutral', 'red');

-- ---------------------------------------------------------------------------
-- companies
-- ---------------------------------------------------------------------------
-- One row per unique company. Dedup key: company_id (slug).
-- ---------------------------------------------------------------------------

CREATE TABLE companies (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    UUID         NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001', -- single-tenant default
  company_id   TEXT         NOT NULL,          -- slug, e.g. 'acme-gmbh'
  name         TEXT         NOT NULL,
  base_domain  TEXT,                           -- e.g. 'acme.de'
  meta         JSONB        NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, company_id)               -- dedup scoped per tenant
);

CREATE INDEX idx_companies_company_id ON companies (tenant_id, company_id);

COMMENT ON TABLE  companies             IS 'Deduped list of companies. (tenant_id, company_id) is the stable dedup key.';
COMMENT ON COLUMN companies.tenant_id  IS 'Multi-tenant scope. Default 00000000-...-0001 = single-user mode.';
COMMENT ON COLUMN companies.company_id IS 'Slug generated by Claude: lowercase, dashes.';
COMMENT ON COLUMN companies.meta       IS 'Free-form metadata: LinkedIn URL, industry, headcount, etc.';

-- ---------------------------------------------------------------------------
-- employers
-- ---------------------------------------------------------------------------
-- HR/recruiter contacts. One row per unique person × company.
-- ---------------------------------------------------------------------------

CREATE TABLE employers (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    UUID         NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
  employer_id  TEXT         NOT NULL,          -- usually email address
  company_id   TEXT         NOT NULL,
  name         TEXT,
  meta         JSONB        NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, employer_id),
  FOREIGN KEY (tenant_id, company_id) REFERENCES companies (tenant_id, company_id) ON DELETE CASCADE
);

CREATE INDEX idx_employers_tenant_company  ON employers (tenant_id, company_id);
CREATE INDEX idx_employers_tenant_employer ON employers (tenant_id, employer_id);

COMMENT ON TABLE  employers             IS 'HR/recruiter contacts linked to companies.';
COMMENT ON COLUMN employers.employer_id IS 'Stable ID — typically email. Produced by Claude.';
COMMENT ON COLUMN employers.tenant_id   IS 'Multi-tenant scope key.';

-- ---------------------------------------------------------------------------
-- jobs
-- ---------------------------------------------------------------------------
-- One row per unique vacancy (best-effort dedup via job_id_fuzzy).
-- A single physical job posting may generate multiple job_events.
-- ---------------------------------------------------------------------------

CREATE TABLE jobs (
  id                   UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            UUID              NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
  job_id_fuzzy         TEXT              NOT NULL,         -- dedup key from Claude
  employer_id          TEXT,
  company_id           TEXT              NOT NULL,
  FOREIGN KEY (tenant_id, company_id)  REFERENCES companies (tenant_id, company_id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, employer_id) REFERENCES employers (tenant_id, employer_id) ON DELETE SET NULL,

  -- Position
  job_title            TEXT,
  location             TEXT,
  seniority            seniority_enum,
  work_mode            work_mode_enum,
  work_mode_raw        TEXT,
  working_hours        TEXT,

  -- Salary
  salary_currency      TEXT,
  salary_min           NUMERIC(12, 2),
  salary_max           NUMERIC(12, 2),
  salary_period        salary_period_enum,

  -- Requirements
  tech_stack           TEXT[]            NOT NULL DEFAULT '{}',
  key_requirements     TEXT[]            NOT NULL DEFAULT '{}',

  -- Process state (latest known)
  current_stage        job_stage_enum    DEFAULT 'discovered',
  priority             priority_enum,
  priority_level       SMALLINT          CHECK (priority_level BETWEEN 1 AND 3),

  -- Dates (latest known)
  interview_date       TIMESTAMPTZ,
  response_deadline    DATE,
  application_deadline DATE,

  -- Call tracking
  has_had_call         BOOLEAN           NOT NULL DEFAULT FALSE,
  call_count           SMALLINT          NOT NULL DEFAULT 0,
  last_call_date       DATE,

  -- User evaluation
  user_rating          user_rating_enum  NOT NULL DEFAULT 'unknown',

  -- Source
  source_url           TEXT,
  source_input         input_source_enum,

  -- Summary
  summary              TEXT,

  created_at           TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

-- One canonical job per fuzzy ID per tenant
CREATE UNIQUE INDEX idx_jobs_job_id_fuzzy ON jobs (tenant_id, job_id_fuzzy);

CREATE INDEX idx_jobs_tenant_company    ON jobs (tenant_id, company_id);
CREATE INDEX idx_jobs_tenant_employer   ON jobs (tenant_id, employer_id);
CREATE INDEX idx_jobs_current_stage     ON jobs (tenant_id, current_stage);
CREATE INDEX idx_jobs_interview_date    ON jobs (tenant_id, interview_date) WHERE interview_date IS NOT NULL;
CREATE INDEX idx_jobs_title_trgm        ON jobs USING gin (job_title gin_trgm_ops);
CREATE INDEX idx_jobs_updated_at        ON jobs (tenant_id, updated_at DESC);

COMMENT ON TABLE  jobs               IS 'One row per unique vacancy. Dedup key: (tenant_id, job_id_fuzzy).';
COMMENT ON COLUMN jobs.tenant_id     IS 'Multi-tenant scope key.';
COMMENT ON COLUMN jobs.job_id_fuzzy  IS 'Fuzzy ID from Claude: company_id__title__location. Used for upsert.';
COMMENT ON COLUMN jobs.user_rating   IS 'Set only by user. AI always returns unknown.';
COMMENT ON COLUMN jobs.tech_stack    IS 'Array of normalized technology names. PII-free.';

-- ---------------------------------------------------------------------------
-- job_events
-- ---------------------------------------------------------------------------
-- Immutable log of every parsed input. Multiple events → one job.
-- Preserves full history: stage changes, new interview dates, etc.
-- ---------------------------------------------------------------------------

CREATE TABLE job_events (
  id               UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID              NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
  job_id           UUID              REFERENCES jobs (id) ON DELETE SET NULL,
  job_thread_key   TEXT,                        -- links events in same hiring thread
  job_id_fuzzy     TEXT,                        -- denormalized for lookup before job exists

  -- Source
  input_source     input_source_enum NOT NULL,
  source_detail    TEXT,
  raw_reference    TEXT,                        -- email Message-ID, URL, or form submission ID
  email_account_id TEXT,                        -- 'gmail_main' | 'mailde_main' | null
  email_date       TIMESTAMPTZ,

  -- Classification
  category         job_category_enum,
  is_job_related   BOOLEAN           NOT NULL DEFAULT TRUE,
  action           TEXT,                        -- action hint from Claude

  -- Stage snapshot at time of event
  stage            job_stage_enum,
  priority         priority_enum,
  priority_level   SMALLINT,

  -- Date snapshot at time of event
  interview_date       TIMESTAMPTZ,
  response_deadline    DATE,
  application_deadline DATE,

  -- Call snapshot
  call_platform    call_platform_enum,
  call_platform_raw TEXT,

  -- Raw data (kept for audit / re-parsing)
  -- SECURITY: raw_text may contain PII (email body).
  -- Consider nulling after retention period (e.g. 90 days via cron).
  -- For blobs > 64KB, store ref in raw_storage_ref instead.
  raw_text         TEXT,
  raw_storage_ref  TEXT,                        -- Telegram file_id, S3 key, or similar
  parsed_json      JSONB             NOT NULL,  -- full Claude output, always kept

  created_at       TIMESTAMPTZ       NOT NULL DEFAULT NOW()
  -- NOTE: No updated_at — job_events is APPEND-ONLY. Never UPDATE or DELETE.
);

CREATE INDEX idx_job_events_tenant_job_id    ON job_events (tenant_id, job_id);
CREATE INDEX idx_job_events_tenant_fuzzy     ON job_events (tenant_id, job_id_fuzzy);
CREATE INDEX idx_job_events_job_thread_key   ON job_events (tenant_id, job_thread_key);
CREATE INDEX idx_job_events_email_account    ON job_events (tenant_id, email_account_id);
CREATE INDEX idx_job_events_email_date       ON job_events (email_date);
CREATE INDEX idx_job_events_category         ON job_events (category);
CREATE INDEX idx_job_events_created_at       ON job_events (tenant_id, created_at DESC);

COMMENT ON TABLE  job_events                 IS 'Append-only event log. Each parsed input = one row. Never UPDATE or DELETE.';
COMMENT ON COLUMN job_events.tenant_id       IS 'Multi-tenant scope key.';
COMMENT ON COLUMN job_events.parsed_json     IS 'Full JSON returned by Claude. Kept permanently for audit/re-parse.';
COMMENT ON COLUMN job_events.raw_text        IS 'PII! Original text. May be nulled after retention period.';
COMMENT ON COLUMN job_events.raw_storage_ref IS 'Pointer to blob storage (Telegram file_id, S3 key) for large bodies.';
COMMENT ON COLUMN job_events.job_id          IS 'FK to jobs. NULL until n8n matches/creates the job.';
COMMENT ON COLUMN job_events.email_account_id IS 'gmail_main | mailde_main. Denormalized for fast filtering.';

-- ---------------------------------------------------------------------------
-- Trigger: auto-update updated_at
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_companies_updated_at
  BEFORE UPDATE ON companies
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_employers_updated_at
  BEFORE UPDATE ON employers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- Views
-- ---------------------------------------------------------------------------

-- Application tracker view (mirrors Google Sheets / Notion layout)
CREATE OR REPLACE VIEW v_applications AS
SELECT
  j.id                    AS job_id,
  c.name                  AS company,
  e.name                  AS recruiter,
  e.employer_id           AS recruiter_email,
  j.job_title             AS role,
  j.location,
  j.current_stage         AS stage,
  j.priority,
  j.interview_date,
  j.response_deadline,
  j.application_deadline,
  j.call_count,
  j.last_call_date,
  j.salary_min,
  j.salary_max,
  j.salary_currency,
  j.salary_period,
  j.work_mode,
  j.seniority,
  j.tech_stack,
  j.user_rating,
  j.source_url,
  j.summary,
  j.created_at,
  j.updated_at
FROM jobs j
JOIN companies c ON c.company_id = j.company_id
LEFT JOIN employers e ON e.employer_id = j.employer_id
ORDER BY
  j.priority_level ASC NULLS LAST,
  j.interview_date ASC NULLS LAST,
  j.updated_at DESC;

COMMENT ON VIEW v_applications IS 'Main application tracker view. Source for Google Sheets sync.';

-- Recent events feed (last 7 days)
CREATE OR REPLACE VIEW v_recent_events AS
SELECT
  je.id,
  je.email_date,
  c.name                  AS company,
  j.job_title             AS role,
  je.category,
  je.stage,
  je.priority,
  je.interview_date,
  je.call_platform,
  je.input_source,
  je.created_at
FROM job_events je
LEFT JOIN jobs j ON j.id = je.job_id
LEFT JOIN companies c ON c.company_id = j.company_id
WHERE je.created_at >= NOW() - INTERVAL '7 days'
  AND je.is_job_related = TRUE
ORDER BY je.created_at DESC;

COMMENT ON VIEW v_recent_events IS 'Events feed for the last 7 days. Use for Telegram notifications.';

-- ---------------------------------------------------------------------------
-- Database roles (least privilege)
-- ---------------------------------------------------------------------------
-- Run once as superuser after schema creation.
-- Passwords must be set externally (from env, never hardcoded here).
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  -- Application user: read/write job data only
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'jobradar_app') THEN
    CREATE ROLE jobradar_app LOGIN;
  END IF;

  -- Read-only user: analytics, Sheets sync, Grafana
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'jobradar_readonly') THEN
    CREATE ROLE jobradar_readonly LOGIN;
  END IF;
END
$$;

GRANT SELECT, INSERT, UPDATE ON companies, employers, jobs, job_events TO jobradar_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO jobradar_app;
-- job_events: app may INSERT but NOT UPDATE or DELETE (append-only)
REVOKE UPDATE, DELETE ON job_events FROM jobradar_app;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO jobradar_readonly;

-- ---------------------------------------------------------------------------
-- Row Level Security (RLS) — stubs, disabled by default
-- ---------------------------------------------------------------------------
-- Enable per table when adding a second tenant.
-- App must SET LOCAL app.current_tenant_id = '<uuid>' before each query.
-- ---------------------------------------------------------------------------

ALTER TABLE companies  ENABLE ROW LEVEL SECURITY;
ALTER TABLE employers  ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_events ENABLE ROW LEVEL SECURITY;

-- Default permissive policy (single-tenant: all rows visible)
-- Replace with restrictive policy when going multi-tenant:
--   CREATE POLICY tenant_isolation ON jobs
--     USING (tenant_id = current_setting('app.current_tenant_id')::uuid);

CREATE POLICY allow_all_companies  ON companies  FOR ALL USING (true);
CREATE POLICY allow_all_employers  ON employers  FOR ALL USING (true);
CREATE POLICY allow_all_jobs       ON jobs       FOR ALL USING (true);
CREATE POLICY allow_all_job_events ON job_events FOR ALL USING (true);

-- ---------------------------------------------------------------------------
-- PII retention: null raw_text after 90 days
-- ---------------------------------------------------------------------------
-- Schedule this as a cron job (pg_cron extension, or external cron via n8n).
-- parsed_json is kept permanently; only the raw email body is cleared.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION purge_old_raw_text()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE job_events
  SET raw_text = NULL
  WHERE raw_text IS NOT NULL
    AND created_at < NOW() - INTERVAL '90 days';

  RAISE NOTICE 'purge_old_raw_text: completed at %', NOW();
END;
$$;

COMMENT ON FUNCTION purge_old_raw_text() IS
  'Nulls raw_text in job_events older than 90 days. '
  'Schedule via pg_cron: SELECT cron.schedule(''0 3 * * *'', ''SELECT purge_old_raw_text()'');'
  'or via n8n Schedule Trigger → Postgres Execute Query.';

-- ---------------------------------------------------------------------------
-- Schema version tracking
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_versions (
  version     TEXT        PRIMARY KEY,
  applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  description TEXT
);

INSERT INTO schema_versions (version, description)
VALUES ('1.1', 'Add tenant_id, RLS stubs, roles, retention function, raw_storage_ref, email_account_id in job_events')
ON CONFLICT (version) DO NOTHING;
